services:
  xiaozhi-esp32-server:
    image: ccr.ccs.tencentyun.com/xinnan/xiaozhi-esp32-server:latest
    container_name: xiaozhi-esp32-server
    restart: always
    #security_opt:
    #  - seccomp:unconfined
    ports:
      - "8000:8000"
    volumes:
      - ./.config.yaml:/opt/xiaozhi-esp32-server/config.yaml